<Project>
  <PropertyGroup Condition="'$(UseWinUI)' == 'true'">
    <WindowsAppSdkSelfContained>true</WindowsAppSdkSelfContained>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultXamlItems>false</EnableDefaultXamlItems>
  </PropertyGroup>
  <PropertyGroup Condition="'$(UseWinUI)' != 'true'">
    <WindowsAppSdkSelfContained>false</WindowsAppSdkSelfContained>
  </PropertyGroup>

  <!-- Prevent missing AppxPackage assembly execution in CLI / Unpackaged CI builds without disabling future production MSIX pipeline -->
  <Target Name="RemovePayloadDuplicates" Condition="'$(WindowsPackageType)' == 'None' or '$(ContinuousIntegrationBuild)' == 'true'" />
  <Target Name="_GetPriFile" Condition="'$(WindowsPackageType)' == 'None' or '$(ContinuousIntegrationBuild)' == 'true'" />
  <Target Name="GetPriFiles" Condition="'$(WindowsPackageType)' == 'None' or '$(ContinuousIntegrationBuild)' == 'true'" />
  <Target Name="_CalculateAppxPackagePayload" Condition="'$(WindowsPackageType)' == 'None' or '$(ContinuousIntegrationBuild)' == 'true'" />
  <Target Name="_CompileAppxManifest" Condition="'$(WindowsPackageType)' == 'None' or '$(ContinuousIntegrationBuild)' == 'true'" />
</Project>
