<Project>
  <PropertyGroup Condition="'$(UseWinUI)' == 'true'">
    <WindowsAppSdkSelfContained>true</WindowsAppSdkSelfContained>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultXamlItems>false</EnableDefaultXamlItems>
  </PropertyGroup>
  <PropertyGroup Condition="'$(UseWinUI)' != 'true'">
    <WindowsAppSdkSelfContained>false</WindowsAppSdkSelfContained>
  </PropertyGroup>

  <!-- Prevent missing AppxPackage assembly execution in CLI builds -->
  <Target Name="RemovePayloadDuplicates" />
  <Target Name="_GetPriFile" />
  <Target Name="GetPriFiles" />
  <Target Name="_CalculateAppxPackagePayload" />
  <Target Name="_CompileAppxManifest" />
</Project>
