<Project>
  <PropertyGroup>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <NuGetAuditLevel>low</NuGetAuditLevel>
    <WarningsAsErrors>$(WarningsAsErrors);NU1903;NU1904</WarningsAsErrors>
    <DisableHasPackageType>true</DisableHasPackageType>
    <AppxPackage>false</AppxPackage>
    <GenerateAppxPackageOnBuild>false</GenerateAppxPackageOnBuild>
    <AppxGeneratePriEnabled>false</AppxGeneratePriEnabled>
    <EnableMsixTooling>false</EnableMsixTooling>
    <ImportAppxTargets>false</ImportAppxTargets>
    <WindowsPackageType>None</WindowsPackageType>
    <EnablePriGen>false</EnablePriGen>
    <SkipWriteAppxManifest>true</SkipWriteAppxManifest>
  </PropertyGroup>
</Project>
