<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <OutputType>WinExe</OutputType>
    <UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <WindowsAppSdkSelfContained>true</WindowsAppSdkSelfContained>
    <EnableMsixTooling>false</EnableMsixTooling>
    <DisableWinUIXamlCompilerTask>false</DisableWinUIXamlCompilerTask>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableDefaultPageItems>true</EnableDefaultPageItems>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
    <EnableDefaultXamlItems>true</EnableDefaultXamlItems>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
  </ItemGroup>

</Project>
